### ISSUE TITLE
How to format to other base?

### ISSUE THREAD

**Issue by oovm** [cmpute/dashu#27]
怎么把 IBig, UBig 这些变成非十进制的字符串? 需要一个 from_str_radix 的反函数.

**Comment by cmpute** [comment]
用官方的fmt接口就可以
```
let n = UBig::from_str_radix("1234", 10);
let s = format!("{:X}", n);
```

如果想转换成任意进制可以使用[`in_radix`](https://docs.rs/dashu/0.3.1/dashu/integer/struct.IBig.html#method.in_radix)函数。

这些我之后都会放到guide里面，不过最近没什么时间写guide 😢
