### ISSUE TITLE
Gcd for IBig returns UBig

### ISSUE THREAD

**Issue by joseluis** [cmpute/dashu#32]
Would it be possible to make it a closed operation, like the rest, that returns the same operand type?

**Comment by cmpute** [comment]
Is there any necessary use case for this change? You can convert the `UBig` result into `IBig` by a single `.into()` expression.

**Comment by joseluis** [comment]
Right, I guess can use the Into impl without performance loss I assume.

I was just porting some code that used the ibig crate to dashu-int and it felt weird that the function returned a different type, and was wondering if there was a good reason for that. The only benefit in anycase may be API-wise.

**Comment by cmpute** [comment]
It's kind of my personal favor. I think it's better to use the most concise type for the output to reduce ambiguity. For example, if the GCD of IBigs returns an IBig, then I can't immediately know what is the sign of the output without looking at the docs.

I will close this issue for now, as I don't plan to change that. Sorry for the confusion.

**Comment by joseluis** [comment]
I understand. I like that it's a consistent choice, I can see the euclidean remainder for IBig is also a UBig. That's good. And since the From<UBig> for IBig impl avoids cloning, it's no issue for me. Thanks for taking the time to explain.
