### ISSUE TITLE
`Display` impl for `FBig` gives wrong result

### ISSUE THREAD

**Issue by Shoeboxam** [cmpute/dashu#48]
The following code outputs `0.1`:
```rust
println!("{}", FBig::<Up>::try_from(0.5)?);
```

However, the internal representation is correct. This passes and outputs `1 * 2 ^ -1 (prec: 53)`:
```rust
assert_eq!(FBig::<Up>::try_from(0.5)?.to_f64().value(), 0.5);
println!("{:?}", FBig::<Up>::try_from(0.5)?);
```

**Comment by cmpute** [comment]
If you use `FBig`, then the representation is in binary digits. That is, `0.1` is the floating point notation in base 2, which is equivalent to 0.5 in base 10. This is a desired behavior ([documented here](https://docs.rs/dashu-float/latest/dashu_float/struct.FBig.html#parsing-and-printing)), though I will make it clearer in the user guide.

**Comment by Shoeboxam** [comment]
Ah, sorry, I wasn't expecting floats to print in base-2, but I guess it makes sense to print in the same B. Thanks for the lib as always!

**Comment by cmpute** [comment]
The major reason I don't want to print in base-10 is that, base conversion can be pretty expensive, and I think it's better to make the conversion explicit,
